#!/usr/bin/env python3
"""
Stock Picker - 智能选股助手
多因子模型选股，输出短期和长期潜力股
"""

from typing import Dict, List, Tuple
from datetime import datetime

# 短期选股因子权重
SHORT_TERM_WEIGHTS = {
    'fund_flow': 0.30,      # 资金流入
    'technical': 0.25,      # 技术形态
    'sentiment': 0.20,      # 情绪热度
    'theme': 0.15,          # 题材催化
    'chip': 0.10,           # 筹码结构
}

# 长期选股因子权重
LONG_TERM_WEIGHTS = {
    'fundamental': 0.30,    # 基本面
    'growth': 0.25,         # 成长性
    'valuation': 0.20,      # 估值修复
    'institution': 0.15,    # 机构动向
    'industry': 0.10,       # 行业景气
}

def calculate_short_term_score(stock: Dict) -> float:
    """
    计算短期综合得分
    
    评分标准（每项1-10分）：
    - 资金流入: 龙虎榜净买入、主力净流入
    - 技术形态: 突破、量价、MACD
    - 情绪热度: 涨停、换手率、人气
    - 题材催化: 热点概念、政策
    - 筹码结构: 股东人数变化
    """
    scores = {
        'fund_flow': min(10, stock.get('net_buy', 0) / 10000 * 2),  # 1亿=2分
        'technical': stock.get('technical_score', 5),
        'sentiment': stock.get('sentiment_score', 5),
        'theme': stock.get('theme_score', 5),
        'chip': stock.get('chip_score', 5),
    }
    
    total = sum(scores[k] * SHORT_TERM_WEIGHTS[k] for k in scores)
    return round(total, 2)

def calculate_long_term_score(stock: Dict) -> float:
    """
    计算长期综合得分
    
    评分标准（每项1-10分）：
    - 基本面: PE、PB、ROE、负债率
    - 成长性: 营收/利润增长
    - 估值修复: 历史分位、行业对比
    - 机构动向: 北向资金、机构持仓
    - 行业景气: 政策支持、周期位置
    """
    scores = {
        'fundamental': stock.get('fundamental_score', 5),
        'growth': stock.get('growth_score', 5),
        'valuation': stock.get('valuation_score', 5),
        'institution': stock.get('institution_score', 5),
        'industry': stock.get('industry_score', 5),
    }
    
    total = sum(scores[k] * LONG_TERM_WEIGHTS[k] for k in scores)
    return round(total, 2)

def generate_picking_report(short_term: List[Dict], long_term: List[Dict]) -> str:
    """生成选股报告"""
    
    report = f"""# 📊 智能选股报告

**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## 📈 短期潜力股 Top 5（1-3个月）

*选股逻辑：资金+技术+情绪+题材+筹码*

"""
    
    for i, stock in enumerate(short_term, 1):
        medal = {1: "🥇", 2: "🥈", 3: "🥉"}.get(i, f"{i}.")
        report += f"""
### {medal} {stock['name']} ({stock['code']})
**综合评分**: {stock['score']}/10 | **行业**: {stock.get('industry', 'N/A')}

**入选理由**:
"""
        reasons = stock.get('reasons', [])
        for r in reasons:
            report += f"- {r}\n"
        
        report += f"""
**操作建议**:
- 目标涨幅: {stock.get('target', '+15%~25%')}
- 止损位: {stock.get('stop_loss', '-8%')}
- 建议仓位: {stock.get('position', '5-10%')}

**风险提示**: {stock.get('risk', '市场情绪波动风险')}

---
"""
    
    report += f"""
## 📊 长期潜力股 Top 5（6-12个月）

*选股逻辑：基本面+成长+估值+机构+行业*

"""
    
    for i, stock in enumerate(long_term, 1):
        medal = {1: "🥇", 2: "🥈", 3: "🥉"}.get(i, f"{i}.")
        report += f"""
### {medal} {stock['name']} ({stock['code']})
**综合评分**: {stock['score']}/10 | **行业**: {stock.get('industry', 'N/A')}

**基本面**:
- PE: {stock.get('pe', 'N/A')} | PB: {stock.get('pb', 'N/A')} | ROE: {stock.get('roe', 'N/A')}
- 营收增长: {stock.get('revenue_growth', 'N/A')} | 净利润增长: {stock.get('profit_growth', 'N/A')}

**入选理由**:
"""
        reasons = stock.get('reasons', [])
        for r in reasons:
            report += f"- {r}\n"
        
        report += f"""
**操作建议**:
- 目标涨幅: {stock.get('target', '+30%~50%')}
- 止损位: {stock.get('stop_loss', '-15%')}
- 建议仓位: {stock.get('position', '10-20%')}
- 持有周期: 6-12个月

**风险提示**: {stock.get('risk', '行业周期下行风险')}

---
"""
    
    report += f"""
## 📋 选股方法论

### 短期选股因子权重
| 因子 | 权重 | 说明 |
|------|------|------|
| 资金流入 | 30% | 龙虎榜净买入、主力净流入 |
| 技术形态 | 25% | 突破形态、量价配合 |
| 情绪热度 | 20% | 涨停、换手率、人气 |
| 题材催化 | 15% | 热点概念、政策利好 |
| 筹码结构 | 10% | 股东人数、筹码集中 |

### 长期选股因子权重
| 因子 | 权重 | 说明 |
|------|------|------|
| 基本面 | 30% | PE、PB、ROE、负债率 |
| 成长性 | 25% | 营收/利润增长 |
| 估值修复 | 20% | 历史分位、行业对比 |
| 机构动向 | 15% | 北向资金、机构持仓 |
| 行业景气 | 10% | 政策支持、周期位置 |

---

## ⚠️ 重要声明

1. **本报告仅供学习研究使用，不构成任何投资建议**
2. **股市有风险，投资需谨慎**
3. **选股结果基于公开数据和AI推理，存在不确定性**
4. **建议结合自身风险承受能力做出决策**

---

*Generated by Stock Picker Skill | 数据来源: 同花顺 (10jqka.com.cn)*
"""
    return report

# 示例数据结构
SAMPLE_SHORT_TERM_STOCK = {
    'name': '示例股票',
    'code': '000001',
    'industry': '金融',
    'score': 8.5,
    'net_buy': 50000,  # 万元
    'technical_score': 9,
    'sentiment_score': 8,
    'theme_score': 7,
    'chip_score': 8,
    'reasons': [
        '✅ 龙虎榜三日净买入5亿，资金大幅流入',
        '✅ 突破前期平台，技术形态良好',
        '✅ 当前热点概念，市场情绪高涨',
    ],
    'target': '+20%',
    'stop_loss': '-8%',
    'position': '5-10%',
    'risk': '热点退潮可能导致快速回调',
}

SAMPLE_LONG_TERM_STOCK = {
    'name': '示例蓝筹',
    'code': '600000',
    'industry': '消费',
    'score': 8.8,
    'pe': 15,
    'pb': 2.5,
    'roe': '18%',
    'revenue_growth': '+20%',
    'profit_growth': '+25%',
    'reasons': [
        '✅ 估值处于历史低位，PE仅15倍',
        '✅ ROE维持18%以上，盈利能力稳健',
        '✅ 业绩持续增长，成长确定性高',
    ],
    'target': '+40%',
    'stop_loss': '-15%',
    'position': '15-20%',
    'risk': '行业竞争加剧可能影响利润率',
}

__all__ = [
    'calculate_short_term_score',
    'calculate_long_term_score',
    'generate_picking_report',
]
